FROM redhat/ubi9:9.2

WORKDIR /app

COPY . .

RUN dnf install -y gcc-c++ python3-pip python3-devel

RUN pip3 install micropipenv

RUN micropipenv install

RUN python3 -m spacy download xx_ent_wiki_sm

ENV FLASK_APP=server.py

ENTRYPOINT ["flask", "run", "--host=0.0.0.0", "--port=5002"]

EXPOSE 5002/tcp
