FROM opensuse/leap:15.5

WORKDIR /app

COPY . .

RUN zypper install -y clang gcc gcc-c++ python311 python311-pip python311-devel

RUN pip3 install micropipenv

RUN micropipenv install

RUN python3.11 -m spacy download xx_ent_wiki_sm

ENV FLASK_APP=server.py

ENTRYPOINT ["flask", "run", "--host=0.0.0.0", "--port=5002"]

EXPOSE 5002/tcp
