FROM rockylinux:9.2

WORKDIR /app

COPY . .

RUN dnf install -y clang python3-pip python3-devel micropipenv

RUN micropipenv install

RUN python3 -m spacy download xx_ent_wiki_sm

ENV FLASK_APP=server.py

ENTRYPOINT ["flask", "run", "--host=0.0.0.0", "--port=5002"]

EXPOSE 5002/tcp
