FROM rockylinux:9.2

WORKDIR /app

COPY . .

RUN dnf install -y clang python3-pip python3-devel

RUN pip3 install --user --upgrade pipenv

ENV PATH="/root/.local/bin:${PATH}"

RUN pipenv install

ENV FLASK_APP=server.py

ENTRYPOINT ["pipenv", "run", "flask", "run", "--host=0.0.0.0", "--port=5002"]

EXPOSE 5002/tcp
