FROM opensuse/leap:15.5

WORKDIR /app

COPY . .

RUN zypper install -y clang python311 python311-devel

RUN pip3 install --user --upgrade pipenv

ENV PATH="/root/.local/bin:${PATH}"

RUN pipenv install

ENV FLASK_APP=server.py

ENTRYPOINT ["pipenv", "run", "flask", "run", "--host=0.0.0.0", "--port=5002"]

EXPOSE 5002/tcp
