basePath: /v3
definitions:
  errorpkg.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      moreInfo:
        type: string
      status:
        type: integer
      userMessage:
        type: string
    type: object
  model.Metadata:
    properties:
      extension:
        type: string
      height:
        type: integer
      width:
        type: integer
      zoomLevels:
        items:
          $ref: '#/definitions/model.ZoomLevel'
        type: array
    type: object
  model.Tile:
    properties:
      height:
        type: integer
      lastColWidth:
        type: integer
      lastRowHeight:
        type: integer
      width:
        type: integer
    type: object
  model.ZoomLevel:
    properties:
      cols:
        type: integer
      height:
        type: integer
      index:
        type: integer
      rows:
        type: integer
      scaleDownPercentage:
        type: number
      tile:
        $ref: '#/definitions/model.Tile'
      width:
        type: integer
    type: object
info:
  contact: {}
  title: Voltaserve Mosaic
  version: 3.0.0
paths:
  /health:
    get:
      description: Get
      operationId: health_get
      produces:
      - text/plain
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Get
      tags:
      - Health
  /mosaics:
    post:
      consumes:
      - multipart/form-data
      description: Create
      operationId: mosaics_create
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      - description: S3 Key
        in: formData
        name: s3_key
        required: true
        type: string
      - description: S3 Bucket
        in: formData
        name: s3_bucket
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Metadata'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Create
      tags:
      - Mosaics
  /mosaics/{s3_bucket}/{s3_key}:
    delete:
      description: Delete
      operationId: mosaics_delete
      parameters:
      - description: S3 Bucket
        in: path
        name: s3_bucket
        required: true
        type: string
      - description: S3 Key
        in: path
        name: s3_key
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Delete
      tags:
      - Mosaics
  /mosaics/{s3_bucket}/{s3_key}/metadata:
    get:
      description: Get Metadata
      operationId: mosaics_get_metadata
      parameters:
      - description: S3 Bucket
        in: path
        name: s3_bucket
        required: true
        type: string
      - description: S3 Key
        in: path
        name: s3_key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Metadata'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Get Metadata
      tags:
      - Mosaics
  /mosaics/{s3_bucket}/{s3_key}/zoom_level/{zoom_level}/row/{row}/column/{column}/extension/{extension}:
    get:
      description: Download Tile
      operationId: mosaics_download_tile
      parameters:
      - description: S3 Bucket
        in: path
        name: s3_bucket
        required: true
        type: string
      - description: S3 Key
        in: path
        name: s3_key
        required: true
        type: string
      - description: Zoom Level
        in: path
        name: zoom_level
        required: true
        type: integer
      - description: Row
        in: path
        name: row
        required: true
        type: integer
      - description: Column
        in: path
        name: column
        required: true
        type: integer
      - description: Extension
        in: path
        name: extension
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Download Tile
      tags:
      - Mosaics
  /version:
    get:
      description: Get
      operationId: version_get
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Get
      tags:
      - Version
swagger: "2.0"
