volumes:
  cockroach:
  minio:
  meilisearch:
  redis:

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v23.2
    ports:
      - ${VOLTASERVE_POSTGRES_PORT}:26257
      - ${VOLTASERVE_COCKROACH_CONSOLE_PORT}:8080
    environment:
      COCKROACH_DATABASE: voltaserve
      COCKROACH_USER: voltaserve
    volumes:
      - cockroach:/cockroach/cockroach-data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: start-single-node --insecure
    healthcheck:
      test: cockroach sql --insecure --execute='SELECT 1;' || exit 1
  minio:
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z
    ports:
      - ${VOLTASERVE_MINIO_PORT}:9000
      - ${VOLTASERVE_MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: voltaserve
      MINIO_ROOT_PASSWORD: voltaserve
      MINIO_REGION: us-east-1
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: curl --fail http://127.0.0.1:9000/health/ready || exit 1
  meilisearch:
    image: getmeili/meilisearch:v1.7
    ports:
      - ${VOLTASERVE_MEILISEARCH_PORT}:7700
    volumes:
      - meilisearch:/meili_data
    healthcheck:
      test: curl --fail http://127.0.0.1:7700/health || exit 1
  redis:
    image: redis:7.2
    ports:
      - ${VOLTASERVE_REDIS_PORT}:6379
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping || exit 1
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - ${VOLTASERVE_MAILHOG_SMTP_PORT}:1025
      - ${VOLTASERVE_MAILHOG_WEB_PORT}:8025
    healthcheck:
      test: wget -q --spider http://127.0.0.1:8025/api/v2/messages || exit 1
  api:
    image: voltaserve/api
    build:
      context: ./api
    ports:
      - ${VOLTASERVE_API_PORT}:8080
    environment:
      - PORT=8080
      - CONVERSION_URL=http://conversion:8083
      - LANGUAGE_URL=http://language:8084
      - MOSAIC_URL=http://mosaic:8085
      - POSTGRES_URL=postgresql://voltaserve@cockroach:26257/voltaserve
      - S3_URL=minio:9000
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - REDIS_ADDRESS=redis:6379
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/v2/health || exit 1
    depends_on:
      - cockroach
      - redis
      - minio
      - meilisearch
    restart: on-failure
  idp:
    image: voltaserve/idp
    build:
      context: ./idp
    ports:
      - ${VOLTASERVE_IDP_PORT}:8081
    environment:
      - PORT=8081
      - POSTGRES_URL=postgresql://voltaserve@cockroach:26257/voltaserve
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    healthcheck:
      test: curl --fail http://127.0.0.1:8081/v2/health || exit 1
    depends_on:
      - cockroach
      - meilisearch
      - minio
    restart: on-failure
  ui:
    image: voltaserve/ui
    build:
      context: ./ui
    ports:
      - ${VOLTASERVE_UI_PORT}:3000
    environment:
      - API_URL=http://api:8080
      - IDP_URL=http://idp:8081
    healthcheck:
      test: curl --fail http://127.0.0.1:3000/index.html || exit 1
    depends_on:
      - idp
      - api
    restart: on-failure
  webdav:
    image: voltaserve/webdav
    build:
      context: ./webdav
    ports:
      - ${VOLTASERVE_WEBDAV_PORT}:8082
    environment:
      - PORT=8082
      - IDP_URL=http://idp:8081
      - API_URL=http://api:8080
    healthcheck:
      test: curl --fail http://127.0.0.1:8082/v2/health || exit 1
    depends_on:
      - idp
      - api
    restart: on-failure
  conversion:
    image: voltaserve/conversion
    build:
      context: ./conversion
    ports:
      - ${VOLTASERVE_CONVERSION_PORT}:8083
    environment:
      - PORT=8083
      - API_URL=http://api:8080
      - S3_URL=minio:9000
    healthcheck:
      test: curl --fail http://127.0.0.1:8083/v2/health || exit 1
    depends_on:
      - api
      - minio
    restart: on-failure
  language:
    image: voltaserve/language
    build:
      context: ./language
    ports:
      - ${VOLTASERVE_LANGUAGE_PORT}:8084
    healthcheck:
      test: curl --fail http://127.0.0.1:8084/v2/health || exit 1
    restart: on-failure
  mosaic:
    image: voltaserve/mosaic
    build:
      context: ./language
    ports:
      - ${VOLTASERVE_MOSAIC_PORT}:8085
    environment:
      - S3_URL=minio:9000
    healthcheck:
      test: curl --fail http://127.0.0.1:8085/v2/health || exit 1
    restart: on-failure
