version: '3.8'

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: voltaserve
    MINIO_ROOT_PASSWORD: voltaserve
    MINIO_REGION: us-east-1
  healthcheck:
    test: ["CMD", "curl", "-f", "http://${VOLTASERVE_HOSTNAME}:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

volumes:
  roach1:
    name: voltaserve-roach1
  roach2:
    name: voltaserve-roach2
  roach3:
    name: voltaserve-roach3
  minio-data1-1:
    name: voltaserve-minio-data1-1
  minio-data1-2:
    name: voltaserve-minio-data1-2
  minio-data2-1:
    name: voltaserve-minio-data2-1
  minio-data2-2:
    name: voltaserve-minio-data2-2
  minio-data3-1:
    name: voltaserve-minio-data3-1
  minio-data3-2:
    name: voltaserve-minio-data3-2
  minio-data4-1:
    name: voltaserve-minio-data4-1
  minio-data4-2:
    name: voltaserve-minio-data4-2
  meilisearch:
    name: voltaserve-meilisearch
  redis:
    name: voltaserve-redis

services:
  roach1:
    container_name: voltaserve-roach1
    hostname: roach1
    image: cockroachdb/cockroach:latest-v23.1
    ports:
      - ${VOLTASERVE_POSTGRES_PORT}:26257
      - ${VOLTASERVE_COCKROACH_CONSOLE_PORT}:8080
    environment:
      COCKROACH_DATABASE: voltaserve
      COCKROACH_USER: voltaserve
    volumes:
      - roach1:/cockroach/cockroach-data
      - ./sql:/docker-entrypoint-initdb.d
    command: start --insecure --join=roach1,roach2,roach3
  roach2:
    container_name: voltaserve-roach2
    hostname: roach2
    image: cockroachdb/cockroach:latest-v23.1
    volumes:
      - roach2:/cockroach/cockroach-data
    command: start --insecure --join=roach1,roach2,roach3
  roach3:
    container_name: voltaserve-roach3
    hostname: roach3
    image: cockroachdb/cockroach:latest-v23.1
    volumes:
      - roach3:/cockroach/cockroach-data
    command: start --insecure --join=roach1,roach2,roach3
  minio1:
    <<: *minio-common
    container_name: voltaserve-minio1
    hostname: minio1
    volumes:
      - minio-data1-1:/data1
      - minio-data1-2:/data2
  minio2:
    <<: *minio-common
    container_name: voltaserve-minio2
    hostname: minio2
    volumes:
      - minio-data2-1:/data1
      - minio-data2-2:/data2
  minio3:
    <<: *minio-common
    container_name: voltaserve-minio3
    hostname: minio3
    volumes:
      - minio-data3-1:/data1
      - minio-data3-2:/data2
  minio4:
    <<: *minio-common
    container_name: voltaserve-minio4
    hostname: minio4
    volumes:
      - minio-data4-1:/data1
      - minio-data4-2:/data2
  minio-nginx:
    container_name: voltaserve-minio-nginx
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${VOLTASERVE_MINIO_PORT}:9000
      - ${VOLTASERVE_MINIO_CONSOLE_PORT}:9001
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
  meilisearch:
    container_name: voltaserve-meilisearch
    image: getmeili/meilisearch:v0.30
    ports:
      - ${VOLTASERVE_MEILISEARCH_PORT}:7700
    volumes:
      - meilisearch:/meili_data
  redis:
    container_name: voltaserve-redis
    image: redis:7.0.8
    ports:
      - ${VOLTASERVE_REDIS_PORT}:6379
    volumes:
      - redis:/data
  mailcatcher:
    container_name: voltaserve-mailcatcher
    image: sj26/mailcatcher:v0.8.2
    ports:
      - ${VOLTASERVE_MAILCATCHER_WEB_PORT}:1080
      - ${VOLTASERVE_MAILCATCHER_SMTP_PORT}:1025