version: "3.9"

volumes:
  postgres:
  minio:
  meilisearch:
  redis:


services:
  postgres:
    image: voltaserve/postgres
    build:
      context: ./postgres
    ports:
      - ${VOLTASERVE_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: voltaserve
      POSTGRES_PASSWORD: voltaserve
    volumes:
      - postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2023-06-19T19-52-50Z
    ports:
      - ${VOLTASERVE_MINIO_PORT}:9000
      - ${VOLTASERVE_MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: voltaserve
      MINIO_ROOT_PASSWORD: voltaserve
      MINIO_REGION: us-east-1
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
  meilisearch:
    image: getmeili/meilisearch:v1.2
    ports:
      - ${VOLTASERVE_MEILISEARCH_PORT}:7700
    volumes:
      - meilisearch:/meili_data
  redis:
    image: redis:7.0
    ports:
      - ${VOLTASERVE_REDIS_PORT}:6379
    volumes:
      - redis:/data
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - ${VOLTASERVE_MAILHOG_SMTP_PORT}:1025
      - ${VOLTASERVE_MAILHOG_WEB_PORT}:8025
  exiftool:
    image: voltaserve/exiftool
    build:
      context: ./tools
      dockerfile: ./docker/${VOLTASERVE_BASE_IMAGE}/Dockerfile.exiftool
    ports:
      - ${VOLTASERVE_EXIFTOOL_PORT}:6001
    environment:
      PORT: 6001
    healthcheck:
      test: curl --fail http://localhost:6001/v1/health || exit 1
    restart: on-failure
  ffmpeg:
    image: voltaserve/ffmpeg
    build:
      context: ./tools
      dockerfile: ./docker/${VOLTASERVE_BASE_IMAGE}/Dockerfile.ffmpeg
    ports:
      - ${VOLTASERVE_FFMPEG_PORT}:6002
    environment:
      PORT: 6002
    healthcheck:
      test: curl --fail http://localhost:6002/v1/health || exit 1
    restart: on-failure
  imagemagick:
    image: voltaserve/imagemagick
    build:
      context: ./tools
      dockerfile: ./docker/${VOLTASERVE_BASE_IMAGE}/Dockerfile.imagemagick
    ports:
      - ${VOLTASERVE_IMAGEMAGICK_PORT}:6003
    environment:
      PORT: 6003
    healthcheck:
      test: curl --fail http://localhost:6003/v1/health || exit 1
    restart: on-failure
  libreoffice:
    image: voltaserve/libreoffice
    build:
      context: ./tools
      dockerfile: ./docker/${VOLTASERVE_BASE_IMAGE}/Dockerfile.libreoffice
    ports:
      - ${VOLTASERVE_LIBREOFFICE_PORT}:6004
    environment:
      PORT: 6004
    healthcheck:
      test: curl --fail http://localhost:6004/v1/health || exit 1
    restart: on-failure
  ocrmypdf:
    image: voltaserve/ocrmypdf
    build:
      context: ./tools
      dockerfile: ./docker/${VOLTASERVE_BASE_IMAGE}/Dockerfile.ocrmypdf
    ports:
      - ${VOLTASERVE_OCRMYPDF_PORT}:6005
    environment:
      PORT: 6005
    healthcheck:
      test: curl --fail http://localhost:6005/v1/health || exit 1
    restart: on-failure
  poppler:
    image: voltaserve/poppler
    build:
      context: ./tools
      dockerfile: ./docker/${VOLTASERVE_BASE_IMAGE}/Dockerfile.poppler
    ports:
      - ${VOLTASERVE_POPPLER_PORT}:6006
    environment:
      PORT: 6006
    healthcheck:
      test: curl --fail http://localhost:6006/v1/health || exit 1
    restart: on-failure
  tesseract:
    image: voltaserve/tesseract
    build:
      context: ./tools
      dockerfile: ./docker/${VOLTASERVE_BASE_IMAGE}/Dockerfile.tesseract
    ports:
      - ${VOLTASERVE_TESSERACT_PORT}:6007
    environment:
      PORT: 6007
    healthcheck:
      test: curl --fail http://localhost:6007/v1/health || exit 1
    restart: on-failure
  api:
    image: voltaserve/api
    build:
      context: ./api
      dockerfile: ./Dockerfile.${VOLTASERVE_BASE_IMAGE}
    ports:
      - ${VOLTASERVE_API_PORT}:5000
    environment:
      - PORT=5000
      - CONVERSION_URL=http://conversion:5001
      - POSTGRES_URL=postgresql://voltaserve:voltaserve@postgres:5432/voltaserve
      - S3_URL=minio:9000
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - REDIS_ADDRESS=redis:6379
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    healthcheck:
      test: curl --fail http://localhost:5000/v1/health || exit 1
    depends_on:
      - postgres
      - redis
      - minio
      - meilisearch
    restart: on-failure
  idp:
    image: voltaserve/idp
    build:
      context: ./idp
      dockerfile: ./Dockerfile.${VOLTASERVE_BASE_IMAGE}
    ports:
      - ${VOLTASERVE_IDP_PORT}:7000
    environment:
      - PORT=7000
      - POSTGRES_URL=postgresql://voltaserve:voltaserve@postgres:5432/voltaserve
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    healthcheck:
      test: curl --fail http://localhost:7000/v1/health || exit 1
    depends_on:
      - postgres
      - meilisearch
      - minio
    restart: on-failure
  ui:
    image: voltaserve/ui
    build:
      context: ./ui
      dockerfile: ./Dockerfile.${VOLTASERVE_BASE_IMAGE}
    ports:
      - ${VOLTASERVE_UI_PORT}:3000
    environment:
      - API_URL=http://api:5000
      - IDP_URL=http://idp:7000
    healthcheck:
      test: curl --fail http://localhost:3000/index.html || exit 1
    depends_on:
      - idp
      - api
    restart: on-failure
  webdav:
    image: voltaserve/webdav
    build:
      context: ./webdav
      dockerfile: ./Dockerfile.${VOLTASERVE_BASE_IMAGE}
    ports:
      - ${VOLTASERVE_WEBDAV_PORT}:6000
    environment:
      - PORT=6000
      - IDP_URL=http://idp:7000
      - API_URL=http://api:5000
    healthcheck:
      test: curl --fail http://localhost:6000/v1/health || exit 1
    depends_on:
      - idp
      - api
    restart: on-failure
  conversion:
    image: voltaserve/conversion
    build:
      context: ./conversion
      dockerfile: ./Dockerfile.${VOLTASERVE_BASE_IMAGE}
    ports:
      - ${VOLTASERVE_CONVERSION_PORT}:5001
    environment:
      - PORT=5001
      - API_URL=http://api:5000
      - LANGUAGE_URL=http://language:5002
      - VOLTASERVE_EXIFTOOL_URL=http://exiftool:6001
      - VOLTASERVE_FFMPEG_URL=http://ffmpeg:6002
      - VOLTASERVE_IMAGEMAGICK_URL=http://imagemagick:6003
      - VOLTASERVE_LIBREOFFICE_URL=http://libreoffice:6004
      - VOLTASERVE_OCRMYPDF_URL=http://ocrmypdf:6005
      - VOLTASERVE_POPPLER_URL=http://poppler:6006
      - VOLTASERVE_TESSERACT_URL=http://tesseract:6007
      - S3_URL=minio:9000
    healthcheck:
      test: curl --fail http://localhost:5001/v1/health || exit 1
    depends_on:
      - api
      - language
      - minio
    restart: on-failure
  language:
    image: voltaserve/language
    build:
      context: ./language
      dockerfile: ./Dockerfile.${VOLTASERVE_BASE_IMAGE}
    ports:
      - ${VOLTASERVE_LANGUAGE_PORT}:5002
    healthcheck:
      test: curl --fail http://localhost:5002/v1/health || exit 1
    restart: on-failure
