version: '3.8'

x-minio-common:
  &minio-common
  image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: voltaserve
    MINIO_ROOT_PASSWORD: voltaserve
    MINIO_REGION: us-east-1
  healthcheck:
    test:
      [
        "CMD",
        "curl",
        "-f",
        "http://${VOLTASERVE_HOSTNAME}:9000/minio/health/live"
      ]
    interval: 30s
    timeout: 20s
    retries: 3

networks:
  voltaserve-net:
    name: voltaserve-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  roach1:
    name: voltaserve-roach1
  roach2:
    name: voltaserve-roach2
  roach3:
    name: voltaserve-roach3
  minio-data1-1:
    name: voltaserve-minio-data1-1
  minio-data1-2:
    name: voltaserve-minio-data1-2
  minio-data2-1:
    name: voltaserve-minio-data2-1
  minio-data2-2:
    name: voltaserve-minio-data2-2
  minio-data3-1:
    name: voltaserve-minio-data3-1
  minio-data3-2:
    name: voltaserve-minio-data3-2
  minio-data4-1:
    name: voltaserve-minio-data4-1
  minio-data4-2:
    name: voltaserve-minio-data4-2
  meilisearch:
    name: voltaserve-meilisearch
  redis-data1:
    name: voltaserve-redis-data1
  redis-data2:
    name: voltaserve-redis-data2
  redis-data3:
    name: voltaserve-redis-data3
  redis-data4:
    name: voltaserve-redis-data4
  redis-data5:
    name: voltaserve-redis-data5
  redis-data6:
    name: voltaserve-redis-data6
  redisinsight:
    name: voltaserve-redisinsight
  conversion-lib:
    name: voltraserve-conversion-lib
  conversion-etc:
    name: voltraserve-conversion-etc
  conversion-bin:
    name: voltraserve-conversion-bin
  conversion-usr:
    name: voltraserve-conversion-usr
  conversion-var:
    name: voltraserve-conversion-var
  conversion-root:
    name: voltraserve-conversion-root
  conversion-opt:
    name: voltraserve-conversion-opt
  conversion-sbin:
    name: voltraserve-conversion-sbin
  conversion-home:
    name: voltraserve-conversion-home
  conversion-go:
    name: voltraserve-conversion-go

services:
  roach1:
    container_name: voltaserve-roach1
    hostname: roach1
    image: cockroachdb/cockroach:latest-v23.1
    ports:
      - ${VOLTASERVE_POSTGRES_PORT}:26257
      - ${VOLTASERVE_COCKROACH_CONSOLE_PORT}:8080
    volumes:
      - roach1:/cockroach/cockroach-data
    command: start --insecure --join=roach1,roach2,roach3
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.10
  roach2:
    container_name: voltaserve-roach2
    hostname: roach2
    image: cockroachdb/cockroach:latest-v23.1
    volumes:
      - roach2:/cockroach/cockroach-data
    command: start --insecure --join=roach1,roach2,roach3
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.11
  roach3:
    container_name: voltaserve-roach3
    hostname: roach3
    image: cockroachdb/cockroach:latest-v23.1
    volumes:
      - roach3:/cockroach/cockroach-data
    command: start --insecure --join=roach1,roach2,roach3
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.12
  minio-nginx:
    container_name: voltaserve-minio-nginx
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./infra/multi-node/minio-nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${VOLTASERVE_MINIO_PORT}:9000
      - ${VOLTASERVE_MINIO_CONSOLE_PORT}:9001
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.20
  minio1:
    <<: *minio-common
    container_name: voltaserve-minio1
    hostname: minio1
    volumes:
      - minio-data1-1:/data1
      - minio-data1-2:/data2
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.21
  minio2:
    <<: *minio-common
    container_name: voltaserve-minio2
    hostname: minio2
    volumes:
      - minio-data2-1:/data1
      - minio-data2-2:/data2
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.22
  minio3:
    <<: *minio-common
    container_name: voltaserve-minio3
    hostname: minio3
    volumes:
      - minio-data3-1:/data1
      - minio-data3-2:/data2
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.23
  minio4:
    <<: *minio-common
    container_name: voltaserve-minio4
    hostname: minio4
    volumes:
      - minio-data4-1:/data1
      - minio-data4-2:/data2
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.24
  meilisearch:
    container_name: voltaserve-meilisearch
    image: getmeili/meilisearch:v0.30
    ports:
      - ${VOLTASERVE_MEILISEARCH_PORT}:7700
    volumes:
      - meilisearch:/meili_data
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.50
  redis1:
    container_name: voltaserve-redis1
    image: redis:7.0.8
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6373:6373
    volumes:
      - redis-data1:/var/lib/redis
      - ./infra/multi-node/redis1.conf:/usr/local/etc/redis/redis.conf
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.31
  redis2:
    container_name: voltaserve-redis2
    image: redis:7.0.8
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6374:6374
    volumes:
      - redis-data2:/var/lib/redis
      - ./infra/multi-node/redis2.conf:/usr/local/etc/redis/redis.conf
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.32
  redis3:
    container_name: voltaserve-redis3
    image: redis:7.0.8
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6375:6375
    volumes:
      - redis-data3:/var/lib/redis
      - ./infra/multi-node/redis3.conf:/usr/local/etc/redis/redis.conf
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.33
  redis4:
    container_name: voltaserve-redis4
    image: redis:7.0.8
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6376:6376
    volumes:
      - redis-data4:/var/lib/redis
      - ./infra/multi-node/redis4.conf:/usr/local/etc/redis/redis.conf
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.34
  redis5:
    container_name: voltaserve-redis5
    image: redis:7.0.8
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6377:6377
    volumes:
      - redis-data5:/var/lib/redis
      - ./infra/multi-node/redis5.conf:/usr/local/etc/redis/redis.conf
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.35
  redis6:
    container_name: voltaserve-redis6
    image: redis:7.0.8
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6378:6378
    volumes:
      - redis-data6:/var/lib/redis
      - ./infra/multi-node/redis6.conf:/usr/local/etc/redis/redis.conf
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.36
  redisinsight:
    container_name: voltaserve-redisinsight
    image: redislabs/redisinsight:1.14.0
    ports:
      - ${VOLTASERVE_REDISINSIGHT_PORT}:8001
    volumes:
      - redisinsight:/db
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.37
  mailcatcher:
    container_name: voltaserve-mailcatcher
    image: sj26/mailcatcher:v0.8.2
    ports:
      - ${VOLTASERVE_MAILCATCHER_WEB_PORT}:1080
      - ${VOLTASERVE_MAILCATCHER_SMTP_PORT}:1025
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.60
  api:
    container_name: voltaserve-api
    image: golang:1.20-alpine
    working_dir: /app
    command: sh -c "go run ."
    volumes:
      - ./api:/app
    environment:
      - PORT=5000
      - CONVERSION_URL=http://conversion:5001
      - POSTGRES_URL=postgresql://voltaserve@roach1:26257/voltaserve
      - S3_URL=minio-nginx:9000
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - REDIS_ADDRESS=redis1:6373;redis2:6374;redis3:6375;redis4:6376;redis5:6377;redis6:6378
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    ports:
      - ${VOLTASERVE_API_PORT}:5000
    depends_on:
      - roach1
      - roach2
      - roach3
      - minio-nginx
      - minio1
      - minio2
      - minio3
      - minio4
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
      - meilisearch
    restart: on-failure
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.41
  idp:
    container_name: voltaserve-idp
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    ports:
      - ${VOLTASERVE_IDP_PORT}:7000
    volumes:
      - ./idp:/app
      - /app/node_modules
    environment:
      - PORT=7000
      - POSTGRES_URL=postgresql://voltaserve@roach1:26257/voltaserve
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    depends_on:
      - roach1
      - roach2
      - roach3
    restart: on-failure
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.40
  ui:
    container_name: voltaserve-ui
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - ${VOLTASERVE_UI_PORT}:3000
    environment:
      - API_URL=http://api:5000
      - IDP_URL=http://idp:7000
    depends_on:
      - idp
      - api
    restart: on-failure
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.42
  webdav:
    container_name: voltaserve-webdav
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    volumes:
      - ./webdav:/app
      - /app/node_modules
    ports:
      - ${VOLTASERVE_WEBDAV_PORT}:6000
    environment:
      - PORT=6000
      - IDP_URL=http://idp:7000
      - API_URL=http://api:5000
    depends_on:
      - idp
      - api
    restart: on-failure
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.43
  conversion:
    container_name: voltaserve-conversion
    image: golang:1.20-bullseye
    working_dir: /app
    command: sh -c "./install-deps.sh && go run ."
    ports:
      - ${VOLTASERVE_CONVERSION_PORT}:5001
    environment:
      - PORT=5001
      - API_URL=http://api:5000
      - S3_URL=minio-nginx:9000
    volumes:
      - ./conversion:/app
      - conversion-lib:/lib
      - conversion-etc:/etc
      - conversion-bin:/bin
      - conversion-sbin:/sbin
      - conversion-usr:/usr
      - conversion-var:/var
      - conversion-opt:/opt
      - conversion-root:/root
      - conversion-home:/home
      - conversion-go:/go
    depends_on:
      - api
      - minio
    networks:
      voltaserve-net:
        ipv4_address: 172.20.0.44
