version: "3.9"

volumes:
  postgres:
  minio:
  meilisearch:
  redis:

services:
  infra-postgres:
    image: voltaserve/infra/postgres
    build:
      context: ./postgres
    ports:
      - ${VOLTASERVE_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: voltaserve
      POSTGRES_PASSWORD: voltaserve
    volumes:
      - postgres:/var/lib/postgresql/data
  infra-minio:
    image: minio/minio:RELEASE.2023-06-19T19-52-50Z
    ports:
      - ${VOLTASERVE_MINIO_PORT}:9000
      - ${VOLTASERVE_MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: voltaserve
      MINIO_ROOT_PASSWORD: voltaserve
      MINIO_REGION: us-east-1
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
  infra-meilisearch:
    image: getmeili/meilisearch:v1.2
    ports:
      - ${VOLTASERVE_MEILISEARCH_PORT}:7700
    volumes:
      - meilisearch:/meili_data
  infra-redis:
    image: redis:7.0
    ports:
      - ${VOLTASERVE_REDIS_PORT}:6379
    volumes:
      - redis:/data
  infra-mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - ${VOLTASERVE_MAILHOG_SMTP_PORT}:1025
      - ${VOLTASERVE_MAILHOG_WEB_PORT}:8025
  tools-exiftool:
    image: voltaserve/tools/exiftool
    build:
      context: ./tools
      dockerfile: ./Dockerfile.exiftool
    ports:
      - ${VOLTASERVE_EXIFTOOL_PORT}:6001
    environment:
      PORT: 6001
    healthcheck:
      test: curl --fail http://localhost:6001/v1/health || exit 1
    restart: on-failure
  tools-ffmpeg:
    image: voltaserve/tools/ffmpeg
    build:
      context: ./tools
      dockerfile: ./Dockerfile.ffmpeg
    ports:
      - ${VOLTASERVE_FFMPEG_PORT}:6002
    environment:
      PORT: 6002
    healthcheck:
      test: curl --fail http://localhost:6002/v1/health || exit 1
    restart: on-failure
  tools-imagemagick:
    image: voltaserve/tools/imagemagick
    build:
      context: ./tools
      dockerfile: ./Dockerfile.imagemagick
    ports:
      - ${VOLTASERVE_IMAGEMAGICK_PORT}:6003
    environment:
      PORT: 6003
    healthcheck:
      test: curl --fail http://localhost:6003/v1/health || exit 1
    restart: on-failure
  tools-libreoffice:
    image: voltaserve/tools/libreoffice
    build:
      context: ./tools
      dockerfile: ./Dockerfile.libreoffice
    ports:
      - ${VOLTASERVE_LIBREOFFICE_PORT}:6004
    environment:
      PORT: 6004
    healthcheck:
      test: curl --fail http://localhost:6004/v1/health || exit 1
    restart: on-failure
  tools-ocrmypdf:
    image: voltaserve/tools/ocrmypdf
    build:
      context: ./tools
      dockerfile: ./Dockerfile.ocrmypdf
    ports:
      - ${VOLTASERVE_OCRMYPDF_PORT}:6005
    environment:
      PORT: 6005
    healthcheck:
      test: curl --fail http://localhost:6005/v1/health || exit 1
    restart: on-failure
  tools-poppler:
    image: voltaserve/tools/poppler
    build:
      context: ./tools
      dockerfile: ./Dockerfile.poppler
    ports:
      - ${VOLTASERVE_POPPLER_PORT}:6006
    environment:
      PORT: 6006
    healthcheck:
      test: curl --fail http://localhost:6006/v1/health || exit 1
    restart: on-failure
  tools-tesseract:
    image: voltaserve/tools/tesseract
    build:
      context: ./tools
      dockerfile: ./Dockerfile.tesseract
    ports:
      - ${VOLTASERVE_TESSERACT_PORT}:6007
    environment:
      PORT: 6007
    healthcheck:
      test: curl --fail http://localhost:6007/v1/health || exit 1
    restart: on-failure
  app-api:
    image: voltaserve/app/api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - ${VOLTASERVE_API_PORT}:5000
    environment:
      - PORT=5000
      - CONVERSION_URL=http://app-conversion:5001
      - POSTGRES_URL=postgresql://voltaserve:voltaserve@infra-postgres:5432/voltaserve
      - S3_URL=infra-minio:9000
      - SEARCH_URL=http://infra-meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - REDIS_ADDRESS=infra-redis:6379
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    healthcheck:
      test: curl --fail http://localhost:5000/v1/health || exit 1
    depends_on:
      - infra-postgres
      - infra-redis
      - infra-minio
      - infra-meilisearch
    restart: on-failure
  app-idp:
    image: voltaserve/app/idp
    build:
      context: ./idp
      dockerfile: ./Dockerfile
    ports:
      - ${VOLTASERVE_IDP_PORT}:7000
    environment:
      - PORT=7000
      - POSTGRES_URL=postgresql://voltaserve:voltaserve@infra-postgres:5432/voltaserve
      - SEARCH_URL=http://infra-meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    healthcheck:
      test: curl --fail http://localhost:7000/v1/health || exit 1
    depends_on:
      - infra-postgres
      - infra-meilisearch
      - infra-minio
    restart: on-failure
  app-ui:
    image: voltaserve/app/ui
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - ${VOLTASERVE_UI_PORT}:3000
    environment:
      - API_URL=http://app-api:5000
      - IDP_URL=http://app-idp:7000
    healthcheck:
      test: curl --fail http://localhost:3000/index.html || exit 1
    depends_on:
      - app-idp
      - app-api
    restart: on-failure
  app-webdav:
    image: voltaserve/app/webdav
    build:
      context: ./webdav
      dockerfile: ./Dockerfile
    ports:
      - ${VOLTASERVE_WEBDAV_PORT}:6000
    environment:
      - PORT=6000
      - IDP_URL=http://app-idp:7000
      - API_URL=http://app-api:5000
    healthcheck:
      test: curl --fail http://localhost:6000/v1/health || exit 1
    depends_on:
      - app-idp
      - app-api
    restart: on-failure
  app-conversion:
    image: voltaserve/app/conversion
    build:
      context: ./conversion
      dockerfile: ./Dockerfile
    ports:
      - ${VOLTASERVE_CONVERSION_PORT}:5001
    environment:
      - PORT=5001
      - API_URL=http://app-api:5000
      - LANGUAGE_URL=http://app-language:5002
      - VOLTASERVE_EXIFTOOL_URL=http://tools-exiftool:6001
      - VOLTASERVE_FFMPEG_URL=http://tools-ffmpeg:6002
      - VOLTASERVE_IMAGEMAGICK_URL=http://tools-imagemagick:6003
      - VOLTASERVE_LIBREOFFICE_URL=http://tools-libreoffice:6004
      - VOLTASERVE_OCRMYPDF_URL=http://tools-ocrmypdf:6005
      - VOLTASERVE_POPPLER_URL=http://tools-poppler:6006
      - VOLTASERVE_TESSERACT_URL=http://tools-tesseract:6007
      - S3_URL=infra-minio:9000
    healthcheck:
      test: curl --fail http://localhost:5001/v1/health || exit 1
    depends_on:
      - app-api
      - app-language
      - infra-minio
    restart: on-failure
  app-language:
    image: voltaserve/app/language
    build:
      context: ./language
      dockerfile: ./Dockerfile
    ports:
      - ${VOLTASERVE_LANGUAGE_PORT}:5002
    healthcheck:
      test: curl --fail http://localhost:5002/v1/health || exit 1
    restart: on-failure
