version: '3.8'

volumes:
  cockroach:
    name: voltaserve-cockroach
  minio:
    name: voltaserve-minio
  meilisearch:
    name: voltaserve-meilisearch
  redis:
    name: voltaserve-redis
  redisinsight:
    name: voltaserve-redisinsight
  api-root:
    name: voltaserve-api-root
  api-go:
    name: voltaserve-api-go
  idp-node-modules:
    name: voltaserve-idp-node-modules
  idp-root:
    name: voltaserve-idp-root
  ui-node-modules:
    name: voltaserve-ui-node-modules
  ui-root:
    name: voltaserve-ui-root
  webdav-node-modules:
    name: voltaserve-webdav-node-modules
  webdav-root:
    name: voltaserve-webdav-root
  conversion-lib:
    name: voltraserve-conversion-lib
  conversion-etc:
    name: voltraserve-conversion-etc
  conversion-bin:
    name: voltraserve-conversion-bin
  conversion-usr:
    name: voltraserve-conversion-usr
  conversion-var:
    name: voltraserve-conversion-var
  conversion-root:
    name: voltraserve-conversion-root
  conversion-opt:
    name: voltraserve-conversion-opt
  conversion-sbin:
    name: voltraserve-conversion-sbin
  conversion-home:
    name: voltraserve-conversion-home
  conversion-go:
    name: voltraserve-conversion-go
services:
  cockroach:
    container_name: voltaserve-cockroach
    image: cockroachdb/cockroach:latest-v23.1
    ports:
      - ${VOLTASERVE_POSTGRES_PORT}:26257
      - ${VOLTASERVE_COCKROACH_CONSOLE_PORT}:8080
    environment:
      COCKROACH_DATABASE: voltaserve
      COCKROACH_USER: voltaserve
    volumes:
      - cockroach:/cockroach/cockroach-data
      - ./infra/sql:/docker-entrypoint-initdb.d
    command: start-single-node --insecure
  minio:
    container_name: voltaserve-minio
    image: minio/minio:RELEASE.2023-01-25T00-19-54Z
    ports:
      - ${VOLTASERVE_MINIO_PORT}:9000
      - ${VOLTASERVE_MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: voltaserve
      MINIO_ROOT_PASSWORD: voltaserve
      MINIO_REGION: us-east-1
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
  meilisearch:
    container_name: voltaserve-meilisearch
    image: getmeili/meilisearch:v0.30
    ports:
      - ${VOLTASERVE_MEILISEARCH_PORT}:7700
    volumes:
      - meilisearch:/meili_data
  redis:
    container_name: voltaserve-redis
    image: redis:7.0.8
    ports:
      - ${VOLTASERVE_REDIS_PORT}:6379
    volumes:
      - redis:/data
  redisinsight:
    container_name: voltaserve-redisinsight
    image: redislabs/redisinsight:1.14.0
    ports:
      - ${VOLTASERVE_REDISINSIGHT_PORT}:8001
    volumes:
      - redisinsight:/db
  mailcatcher:
    container_name: voltaserve-mailcatcher
    image: sj26/mailcatcher:v0.8.2
    ports:
      - ${VOLTASERVE_MAILCATCHER_WEB_PORT}:1080
      - ${VOLTASERVE_MAILCATCHER_SMTP_PORT}:1025
  api:
    container_name: voltaserve-api
    image: golang:1.20-alpine
    working_dir: /app
    command: sh -c "go run ."
    ports:
      - ${VOLTASERVE_API_PORT}:5000
    environment:
      - PORT=5000
      - CONVERSION_URL=http://conversion:5001
      - POSTGRES_URL=postgresql://voltaserve@cockroach:26257/voltaserve
      - S3_URL=minio:9000
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - REDIS_ADDRESS=redis:6379
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    volumes:
      - ./api:/app
      - api-root:/root
      - api-go:/go
    healthcheck:
      test: wget --spider --quiet http://localhost:5000/v1/health || exit 1
    depends_on:
      - cockroach
      - redis
      - minio
      - meilisearch
    restart: on-failure
  idp:
    container_name: voltaserve-idp
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    ports:
      - ${VOLTASERVE_IDP_PORT}:7000
    environment:
      - PORT=7000
      - POSTGRES_URL=postgresql://voltaserve@cockroach:26257/voltaserve
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    volumes:
      - ./idp:/app
      - idp-node-modules:/app/node_modules
      - idp-root:/root
    healthcheck:
      test: wget --spider --quiet http://localhost:7000/v1/health || exit 1
    depends_on:
      - cockroach
      - meilisearch
      - minio
    restart: on-failure
  ui:
    container_name: voltaserve-ui
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    ports:
      - ${VOLTASERVE_UI_PORT}:3000
    environment:
      - API_URL=http://api:5000
      - IDP_URL=http://idp:7000
    volumes:
      - ./ui:/app
      - ui-node-modules:/app/node_modules
      - ui-root:/root
    healthcheck:
      test: wget --spider --quiet http://localhost:3000/index.html || exit 1
    depends_on:
      - idp
      - api
    restart: on-failure
  webdav:
    container_name: voltaserve-webdav
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    ports:
      - ${VOLTASERVE_WEBDAV_PORT}:6000
    environment:
      - PORT=6000
      - IDP_URL=http://idp:7000
      - API_URL=http://api:5000
    volumes:
      - ./webdav:/app
      - webdav-node-modules:/app/node_modules
      - webdav-root:/root
    healthcheck:
      test: wget --spider --quiet http://localhost:6000/v1/health || exit 1
    depends_on:
      - idp
      - api
    restart: on-failure
  conversion:
    container_name: voltaserve-conversion
    image: golang:1.20-bullseye
    working_dir: /app
    command: sh -c "./install-deps.sh && go run ."
    ports:
      - ${VOLTASERVE_CONVERSION_PORT}:5001
    environment:
      - PORT=5001
      - API_URL=http://api:5000
      - S3_URL=minio:9000
    volumes:
      - ./conversion:/app
      - conversion-lib:/lib
      - conversion-etc:/etc
      - conversion-bin:/bin
      - conversion-sbin:/sbin
      - conversion-usr:/usr
      - conversion-var:/var
      - conversion-opt:/opt
      - conversion-root:/root
      - conversion-home:/home
      - conversion-go:/go
    healthcheck:
      test: wget --spider --quiet http://localhost:5001/v1/health || exit 1
    depends_on:
      - api
      - minio
    restart: on-failure
