version: '3.8'

volumes:
  cockroach:
  minio:
  meilisearch:
  redis:
  redisinsight:
  api_root:
  api_go:
  idp_root:
  ui_root:
  webdav_root:
  conversion_lib:
  conversion_etc:
  conversion_bin:
  conversion_usr:
  conversion_var:
  conversion_root:
  conversion_opt:
  conversion_sbin:
  conversion_home:
  conversion_go:
services:
  cockroach:
    image: cockroachdb/cockroach:latest-v23.1
    ports:
      - ${VOLTASERVE_POSTGRES_PORT}:26257
      - ${VOLTASERVE_COCKROACH_CONSOLE_PORT}:8080
    environment:
      COCKROACH_DATABASE: voltaserve
      COCKROACH_USER: voltaserve
    volumes:
      - cockroach:/cockroach/cockroach-data
      - ./infra/sql:/docker-entrypoint-initdb.d
    command: start-single-node --insecure
  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    ports:
      - ${VOLTASERVE_MINIO_PORT}:9000
      - ${VOLTASERVE_MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: voltaserve
      MINIO_ROOT_PASSWORD: voltaserve
      MINIO_REGION: us-east-1
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
  meilisearch:
    image: getmeili/meilisearch:v0.30
    ports:
      - ${VOLTASERVE_MEILISEARCH_PORT}:7700
    volumes:
      - meilisearch:/meili_data
  redis:
    image: redis:7.0.8
    ports:
      - ${VOLTASERVE_REDIS_PORT}:6379
    volumes:
      - redis:/data
  redisinsight:
    image: redislabs/redisinsight:1.14.0
    ports:
      - ${VOLTASERVE_REDISINSIGHT_PORT}:8001
    volumes:
      - redisinsight:/db
  mailcatcher:
    image: sj26/mailcatcher:v0.8.2
    ports:
      - ${VOLTASERVE_MAILCATCHER_WEB_PORT}:1080
      - ${VOLTASERVE_MAILCATCHER_SMTP_PORT}:1025
  api:
    image: golang:1.20-alpine
    working_dir: /app
    command: sh -c "go run ."
    ports:
      - ${VOLTASERVE_API_PORT}:5000
    environment:
      - PORT=5000
      - CONVERSION_URL=http://conversion:5001
      - POSTGRES_URL=postgresql://voltaserve@cockroach:26257/voltaserve
      - S3_URL=minio:9000
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - REDIS_ADDRESS=redis:6379
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    volumes:
      - ./api:/app
      - api_root:/root
      - api_go:/go
    healthcheck:
      test: wget --spider --quiet http://localhost:5000/v1/health || exit 1
    depends_on:
      - cockroach
      - redis
      - minio
      - meilisearch
    restart: on-failure
  idp:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "yarn run dev"
    ports:
      - ${VOLTASERVE_IDP_PORT}:7000
    environment:
      - PORT=7000
      - POSTGRES_URL=postgresql://voltaserve@cockroach:26257/voltaserve
      - SEARCH_URL=http://meilisearch:7700
      - PUBLIC_UI_URL=http://${VOLTASERVE_HOSTNAME}:${VOLTASERVE_UI_PORT}
      - SMTP_HOST=${VOLTASERVE_SMTP_HOST}
      - SMTP_PORT=${VOLTASERVE_SMTP_PORT}
      - SMTP_SECURE=${VOLTASERVE_SMTP_SECURE}
      - SMTP_USERNAME=${VOLTASERVE_SMTP_USERNAME}
      - SMTP_PASSWORD=${VOLTASERVE_SMTP_PASSWORD}
      - SMTP_SENDER_ADDRESS=${VOLTASERVE_SMTP_SENDER_ADDRESS}
      - SMTP_SENDER_NAME=${VOLTASERVE_SMTP_SENDER_NAME}
    volumes:
      - ./idp:/app
      - idp_root:/root
    healthcheck:
      test: wget --spider --quiet http://localhost:7000/v1/health || exit 1
    depends_on:
      - cockroach
      - meilisearch
      - minio
    restart: on-failure
  ui:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "yarn run dev"
    ports:
      - ${VOLTASERVE_UI_PORT}:3000
    environment:
      - API_URL=http://api:5000
      - IDP_URL=http://idp:7000
    volumes:
      - ./ui:/app
      - ui_root:/root
    healthcheck:
      test: wget --spider --quiet http://localhost:3000/index.html || exit 1
    depends_on:
      - idp
      - api
    restart: on-failure
  webdav:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "yarn run dev"
    ports:
      - ${VOLTASERVE_WEBDAV_PORT}:6000
    environment:
      - PORT=6000
      - IDP_URL=http://idp:7000
      - API_URL=http://api:5000
    volumes:
      - ./webdav:/app
      - webdav_root:/root
    healthcheck:
      test: wget --spider --quiet http://localhost:6000/v1/health || exit 1
    depends_on:
      - idp
      - api
    restart: on-failure
  conversion:
    image: golang:1.20-bullseye
    working_dir: /app
    command: sh -c "./install-deps.sh && go run ."
    ports:
      - ${VOLTASERVE_CONVERSION_PORT}:5001
    environment:
      - PORT=5001
      - API_URL=http://api:5000
      - S3_URL=minio:9000
    volumes:
      - ./conversion:/app
      - conversion_lib:/lib
      - conversion_etc:/etc
      - conversion_bin:/bin
      - conversion_sbin:/sbin
      - conversion_usr:/usr
      - conversion_var:/var
      - conversion_opt:/opt
      - conversion_root:/root
      - conversion_home:/home
      - conversion_go:/go
    healthcheck:
      test: wget --spider --quiet http://localhost:5001/v1/health || exit 1
    depends_on:
      - api
      - minio
    restart: on-failure
