FROM rockylinux:9.2 AS builder

WORKDIR /build

COPY . .

RUN dnf install -y golang

RUN go mod download
RUN go build -o voltaserve-tools

FROM rockylinux:9.2 AS runner

RUN dnf install -y wget tesseract

WORKDIR /usr/share/tesseract/tessdata

RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/osd.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/eng.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/deu.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/fra.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/nld.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/ita.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/spa.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/por.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/swe.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/jpn.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/chi_sim.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/chi_tra.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/kor.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/hin.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/rus.traineddata
RUN wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/ara.traineddata

WORKDIR /app

COPY --from=builder /build/voltaserve-tools ./voltaserve-tools
COPY --from=builder /build/.env ./.env

ENTRYPOINT ["./voltaserve-tools"]

EXPOSE 6001
