// Code generated by MockGen. DO NOT EDIT.
// Source: guard/organization_guard.go

// Package mocks is a generated GoMock package.
package guard

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/kouprlabs/voltaserve/api/model"
)

// MockOrganizationGuard is a mock of OrganizationGuard interface.
type MockOrganizationGuard struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationGuardMockRecorder
}

// MockOrganizationGuardMockRecorder is the mock recorder for MockOrganizationGuard.
type MockOrganizationGuardMockRecorder struct {
	mock *MockOrganizationGuard
}

// NewMockOrganizationGuard creates a new mock instance.
func NewMockOrganizationGuard(ctrl *gomock.Controller) *MockOrganizationGuard {
	mock := &MockOrganizationGuard{ctrl: ctrl}
	mock.recorder = &MockOrganizationGuardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationGuard) EXPECT() *MockOrganizationGuardMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockOrganizationGuard) Authorize(userID string, org model.Organization, permission string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", userID, org, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authorize indicates an expected call of Authorize.
func (mr *MockOrganizationGuardMockRecorder) Authorize(userID, org, permission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockOrganizationGuard)(nil).Authorize), userID, org, permission)
}

// IsAuthorized mocks base method.
func (m *MockOrganizationGuard) IsAuthorized(userID string, org model.Organization, permission string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorized", userID, org, permission)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAuthorized indicates an expected call of IsAuthorized.
func (mr *MockOrganizationGuardMockRecorder) IsAuthorized(userID, org, permission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorized", reflect.TypeOf((*MockOrganizationGuard)(nil).IsAuthorized), userID, org, permission)
}
