basePath: /v2
definitions:
  api_client.PipelineRunOptions:
    properties:
      bucket:
        type: string
      key:
        type: string
      payload:
        additionalProperties:
          type: string
        type: object
      pipelineId:
        type: string
      snapshotId:
        type: string
      taskId:
        type: string
    type: object
  errorpkg.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      moreInfo:
        type: string
      status:
        type: integer
      userMessage:
        type: string
    type: object
info:
  contact: {}
  title: Voltaserve Conversion
  version: 2.0.0
paths:
  /health:
    get:
      description: Get
      operationId: get_version
      produces:
      - application/json
      responses:
        "200":
          description: '{Version}'
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Get
      tags:
      - Version
  /pipelines/run:
    post:
      consumes:
      - application/json
      description: Run
      operationId: pipelines_run
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api_client.PipelineRunOptions'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Run
      tags:
      - Pipelines
swagger: "2.0"
