basePath: /v3
definitions:
  dto.PipelineRunOptions:
    properties:
      bucket:
        type: string
      intent:
        type: string
      key:
        type: string
      language:
        type: string
      payload:
        additionalProperties:
          type: string
        type: object
      pipelineId:
        type: string
      snapshotId:
        type: string
      taskId:
        type: string
    required:
    - bucket
    - key
    - snapshotId
    type: object
  errorpkg.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      moreInfo:
        type: string
      status:
        type: integer
      userMessage:
        type: string
    type: object
info:
  contact: {}
  title: Voltaserve Conversion
  version: 3.0.0
paths:
  /health:
    get:
      description: Get
      operationId: health_get
      produces:
      - text/plain
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Get
      tags:
      - Health
  /pipelines/run:
    post:
      consumes:
      - application/json
      description: Run
      operationId: pipelines_run
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.PipelineRunOptions'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Run
      tags:
      - Pipelines
  /version:
    get:
      description: Get
      operationId: version_get
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Get
      tags:
      - Version
swagger: "2.0"
