basePath: /v2
definitions:
  client.PipelineRunOptions:
    properties:
      bucket:
        type: string
      key:
        type: string
      payload:
        additionalProperties:
          type: string
        type: object
      pipelineId:
        type: string
      snapshotId:
        type: string
      taskId:
        type: string
    type: object
  errorpkg.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      moreInfo:
        type: string
      status:
        type: integer
      userMessage:
        type: string
    type: object
  service.ToolRunOptions:
    properties:
      args:
        items:
          type: string
        type: array
      bin:
        type: string
      stdout:
        type: boolean
    type: object
info:
  contact: {}
  title: Voltaserve Conversion
  version: 2.0.0
paths:
  /health:
    get:
      description: Get Health
      operationId: get_health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/errorpkg.ErrorResponse'
      summary: Get Health
      tags:
      - Health
  /pipelines/run:
    post:
      consumes:
      - application/json
      description: Run
      operationId: pipeline_run
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/client.PipelineRunOptions'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Run
      tags:
      - Pipelines
  /tools/run:
    post:
      consumes:
      - application/json
      description: Run
      operationId: tools_run
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/service.ToolRunOptions'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Run
      tags:
      - Tools
swagger: "2.0"
