// Code generated by MockGen. DO NOT EDIT.
// Source: service/invitation_mapper.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/kouprlabs/voltaserve/api/model"
)

// MockInvitationMapper is a mock of InvitationMapper interface.
type MockInvitationMapper struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationMapperMockRecorder
}

// MockInvitationMapperMockRecorder is the mock recorder for MockInvitationMapper.
type MockInvitationMapperMockRecorder struct {
	mock *MockInvitationMapper
}

// NewMockInvitationMapper creates a new mock instance.
func NewMockInvitationMapper(ctrl *gomock.Controller) *MockInvitationMapper {
	mock := &MockInvitationMapper{ctrl: ctrl}
	mock.recorder = &MockInvitationMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationMapper) EXPECT() *MockInvitationMapperMockRecorder {
	return m.recorder
}

// mapMany mocks base method.
func (m *MockInvitationMapper) mapMany(arg0 []model.Invitation, arg1 string) ([]*Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "mapMany", arg0, arg1)
	ret0, _ := ret[0].([]*Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// mapMany indicates an expected call of mapMany.
func (mr *MockInvitationMapperMockRecorder) mapMany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mapMany", reflect.TypeOf((*MockInvitationMapper)(nil).mapMany), arg0, arg1)
}

// mapOne mocks base method.
func (m *MockInvitationMapper) mapOne(arg0 model.Invitation, arg1 string) (*Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "mapOne", arg0, arg1)
	ret0, _ := ret[0].(*Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// mapOne indicates an expected call of mapOne.
func (mr *MockInvitationMapperMockRecorder) mapOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mapOne", reflect.TypeOf((*MockInvitationMapper)(nil).mapOne), arg0, arg1)
}
