// Code generated by MockGen. DO NOT EDIT.
// Source: service/organization_mapper.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/kouprlabs/voltaserve/api/model"
)

// MockOrganizationMapper is a mock of OrganizationMapper interface.
type MockOrganizationMapper struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationMapperMockRecorder
}

// MockOrganizationMapperMockRecorder is the mock recorder for MockOrganizationMapper.
type MockOrganizationMapperMockRecorder struct {
	mock *MockOrganizationMapper
}

// NewMockOrganizationMapper creates a new mock instance.
func NewMockOrganizationMapper(ctrl *gomock.Controller) *MockOrganizationMapper {
	mock := &MockOrganizationMapper{ctrl: ctrl}
	mock.recorder = &MockOrganizationMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationMapper) EXPECT() *MockOrganizationMapperMockRecorder {
	return m.recorder
}

// mapMany mocks base method.
func (m *MockOrganizationMapper) mapMany(arg0 []model.Organization, arg1 string) ([]*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "mapMany", arg0, arg1)
	ret0, _ := ret[0].([]*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// mapMany indicates an expected call of mapMany.
func (mr *MockOrganizationMapperMockRecorder) mapMany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mapMany", reflect.TypeOf((*MockOrganizationMapper)(nil).mapMany), arg0, arg1)
}

// mapOne mocks base method.
func (m *MockOrganizationMapper) mapOne(arg0 model.Organization, arg1 string) (*Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "mapOne", arg0, arg1)
	ret0, _ := ret[0].(*Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// mapOne indicates an expected call of mapOne.
func (mr *MockOrganizationMapperMockRecorder) mapOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mapOne", reflect.TypeOf((*MockOrganizationMapper)(nil).mapOne), arg0, arg1)
}
