// Code generated by MockGen. DO NOT EDIT.
// Source: service/workspace_mapper.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/kouprlabs/voltaserve/api/model"
)

// MockWorkspaceMapper is a mock of WorkspaceMapper interface.
type MockWorkspaceMapper struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMapperMockRecorder
}

// MockWorkspaceMapperMockRecorder is the mock recorder for MockWorkspaceMapper.
type MockWorkspaceMapperMockRecorder struct {
	mock *MockWorkspaceMapper
}

// NewMockWorkspaceMapper creates a new mock instance.
func NewMockWorkspaceMapper(ctrl *gomock.Controller) *MockWorkspaceMapper {
	mock := &MockWorkspaceMapper{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceMapper) EXPECT() *MockWorkspaceMapperMockRecorder {
	return m.recorder
}

// mapMany mocks base method.
func (m *MockWorkspaceMapper) mapMany(arg0 []model.Workspace, arg1 string) ([]*Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "mapMany", arg0, arg1)
	ret0, _ := ret[0].([]*Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// mapMany indicates an expected call of mapMany.
func (mr *MockWorkspaceMapperMockRecorder) mapMany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mapMany", reflect.TypeOf((*MockWorkspaceMapper)(nil).mapMany), arg0, arg1)
}

// mapOne mocks base method.
func (m *MockWorkspaceMapper) mapOne(arg0 model.Workspace, arg1 string) (*Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "mapOne", arg0, arg1)
	ret0, _ := ret[0].(*Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// mapOne indicates an expected call of mapOne.
func (mr *MockWorkspaceMapperMockRecorder) mapOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mapOne", reflect.TypeOf((*MockWorkspaceMapper)(nil).mapOne), arg0, arg1)
}
