FROM voltaserve/tools

RUN zypper install -y GraphicsMagick \
    ghostscript \
    libpoppler-cpp0 \
    libjpeg8 \
    libpng16-16 \
    libtiff5 \
    liblcms2-2 \
    libfreetype6 \
    libgif7 \
    libwebp6 \
    libwmf-0_2-7 \
    libXext6 \
    libMagickCore-7_Q16HDRI10 \
    libMagickWand-7_Q16HDRI10