FROM ubuntu:23.04 as builder

WORKDIR /build

COPY . .

RUN apt-get update
RUN apt-get install -y ca-certificates
RUN update-ca-certificates
RUN apt-get install -y golang

RUN go mod download
RUN go build -o voltaserve-tools

FROM ubuntu:23.04 AS runner

RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y ocrmypdf

WORKDIR /usr/share/tesseract-ocr/5/tessdata

RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/osd.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/eng.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/deu.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/fra.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/nld.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/ita.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/spa.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/por.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/swe.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/fin.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/jpn.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/chi_sim.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/chi_tra.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/kor.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/hin.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/rus.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/ara.traineddata

WORKDIR /app

COPY --from=builder /build/voltaserve-tools ./voltaserve-tools
COPY --from=builder /build/.env ./.env

ENTRYPOINT ["./voltaserve-tools"]

EXPOSE 6001