FROM voltaserve/tools

RUN zypper install -y ImageMagick ghostscript

RUN policy_path=$(identify -list policy | awk '/Path:/ {print $2}' | sed 's/\[built-in\]//') \
    && awk '/pattern="(PS|PS2|PS3|PDF|XPS|EPS|PCL)"/ { sub(/rights="write"/, "rights=\"read|write\"") } { print }' "$policy_path" > "$policy_path.tmp" \
    && mv "$policy_path.tmp" "$policy_path"