FROM voltaserve/tools

RUN zypper install -y tesseract-ocr
RUN zypper install -y wget

WORKDIR /usr/share/tesseract/tessdata

RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/osd.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/eng.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/deu.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/fra.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/nld.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/ita.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/spa.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/por.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/swe.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/fin.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/jpn.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/chi_sim.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/chi_tra.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/kor.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/hin.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/rus.traineddata
RUN wget https://github.com/kouprlabs/tessdata/raw/4.1.0/ara.traineddata