// Code generated by MockGen. DO NOT EDIT.
// Source: cache/organization_cache.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kouprlabs/voltaserve/api/model"
)

// MockOrganizationCache is a mock of OrganizationCache interface.
type MockOrganizationCache struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationCacheMockRecorder
}

// MockOrganizationCacheMockRecorder is the mock recorder for MockOrganizationCache.
type MockOrganizationCacheMockRecorder struct {
	mock *MockOrganizationCache
}

// NewMockOrganizationCache creates a new mock instance.
func NewMockOrganizationCache(ctrl *gomock.Controller) *MockOrganizationCache {
	mock := &MockOrganizationCache{ctrl: ctrl}
	mock.recorder = &MockOrganizationCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationCache) EXPECT() *MockOrganizationCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockOrganizationCache) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationCacheMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationCache)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockOrganizationCache) Get(id string) (model.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(model.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrganizationCacheMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrganizationCache)(nil).Get), id)
}

// Refresh mocks base method.
func (m *MockOrganizationCache) Refresh(id string) (model.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", id)
	ret0, _ := ret[0].(model.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockOrganizationCacheMockRecorder) Refresh(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockOrganizationCache)(nil).Refresh), id)
}

// Set mocks base method.
func (m *MockOrganizationCache) Set(organization model.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", organization)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockOrganizationCacheMockRecorder) Set(organization interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockOrganizationCache)(nil).Set), organization)
}
