// Code generated by MockGen. DO NOT EDIT.
// Source: search/task_search.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	infra "github.com/kouprlabs/voltaserve/api/infra"
	model "github.com/kouprlabs/voltaserve/api/model"
)

// MockTaskSearch is a mock of TaskSearch interface.
type MockTaskSearch struct {
	ctrl     *gomock.Controller
	recorder *MockTaskSearchMockRecorder
}

// MockTaskSearchMockRecorder is the mock recorder for MockTaskSearch.
type MockTaskSearchMockRecorder struct {
	mock *MockTaskSearch
}

// NewMockTaskSearch creates a new mock instance.
func NewMockTaskSearch(ctrl *gomock.Controller) *MockTaskSearch {
	mock := &MockTaskSearch{ctrl: ctrl}
	mock.recorder = &MockTaskSearchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskSearch) EXPECT() *MockTaskSearchMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTaskSearch) Delete(ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskSearchMockRecorder) Delete(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskSearch)(nil).Delete), ids)
}

// Index mocks base method.
func (m *MockTaskSearch) Index(tasks []model.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockTaskSearchMockRecorder) Index(tasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockTaskSearch)(nil).Index), tasks)
}

// Query mocks base method.
func (m *MockTaskSearch) Query(query string, opts infra.QueryOptions) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", query, opts)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockTaskSearchMockRecorder) Query(query, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockTaskSearch)(nil).Query), query, opts)
}

// Update mocks base method.
func (m *MockTaskSearch) Update(tasks []model.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskSearchMockRecorder) Update(tasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskSearch)(nil).Update), tasks)
}
