// Code generated by MockGen. DO NOT EDIT.
// Source: guard/workspace_guard.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/kouprlabs/voltaserve/api/model"
)

// MockWorkspaceGuard is a mock of WorkspaceGuard interface.
type MockWorkspaceGuard struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceGuardMockRecorder
}

// MockWorkspaceGuardMockRecorder is the mock recorder for MockWorkspaceGuard.
type MockWorkspaceGuardMockRecorder struct {
	mock *MockWorkspaceGuard
}

// NewMockWorkspaceGuard creates a new mock instance.
func NewMockWorkspaceGuard(ctrl *gomock.Controller) *MockWorkspaceGuard {
	mock := &MockWorkspaceGuard{ctrl: ctrl}
	mock.recorder = &MockWorkspaceGuardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceGuard) EXPECT() *MockWorkspaceGuardMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockWorkspaceGuard) Authorize(userID string, workspace model.Workspace, permission string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", userID, workspace, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authorize indicates an expected call of Authorize.
func (mr *MockWorkspaceGuardMockRecorder) Authorize(userID, workspace, permission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockWorkspaceGuard)(nil).Authorize), userID, workspace, permission)
}

// IsAuthorized mocks base method.
func (m *MockWorkspaceGuard) IsAuthorized(userID string, workspace model.Workspace, permission string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorized", userID, workspace, permission)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAuthorized indicates an expected call of IsAuthorized.
func (mr *MockWorkspaceGuardMockRecorder) IsAuthorized(userID, workspace, permission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorized", reflect.TypeOf((*MockWorkspaceGuard)(nil).IsAuthorized), userID, workspace, permission)
}
