# Copyright 2024 Daniël Sonck, Piotr Łoboda.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the GNU Affero General Public License v3.0 only, included in the file
# licenses/AGPL.txt.

name: Lin and build voltaserve/conversion

on:
  pull_request:
    branches:
      - main
    paths:
      - "conversion/**"
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint using Golanci lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: conversion
    permissions:
      contents: read
      pull-requests: read
      checks: write

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64, amd64

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./conversion
          push: false
          platforms: linux/amd64,linux/arm64