# Copyright 2024 Daniël Sonck, Piotr Łoboda.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the GNU Affero General Public License v3.0 only, included in the file
# licenses/AGPL.txt.

name: Lint voltaserve/console

on:
  pull_request:
    branches:
      - main
    paths:
      - "console/**"
      - "!console/.env"
      - "!console/README.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Lint using flake8
        uses: py-actions/flake8@v2
        with:
          path: console
          ignore: "F401,W291,W503"
          max-line-length: "120"
          exclude: ".git,Dockerfile"

    permissions:
      contents: read
      pull-requests: read
      checks: write

  build:
    needs: lint
    name: build-${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["arm64", "amd64"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./console
          push: false
          platforms: linux/${{ matrix.platform }}

