# Copyright 2024 Daniël Sonck, Piotr Łoboda.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the GNU Affero General Public License v3.0 only, included in the file
# licenses/AGPL.txt.

name: Lint and build voltaserve/ui

on:
  pull_request:
    branches:
      - main
    paths:
      - "ui/**"
      - "!ui/.env"
      - "!ui/README.md"
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add dummy embedded files
        run: |
          mkdir ui/dist
          touch ui/dist/index.html

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages
        run: npm i --legacy-peer-deps
        working-directory: ui
  
      - name: Run TypeScript Compiler
        run: npm run tsc
        working-directory: ui

      - name: Run ESLint
        run: npm run lint
        working-directory: ui
    permissions:
      contents: read
      pull-requests: read
      checks: write

  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        platform: [ "arm64", "amd64" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          push: false
          platforms: linux/${{ matrix.platform }}