# Copyright (c) 2024 Daniël Sonck, Piotr Łoboda.
#
# Use of this software is governed by the Business Source License
# included in the file LICENSE in the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the GNU Affero General Public License v3.0 only, included in the file
# AGPL-3.0-only in the root of this repository.

name: Voltaserve UI

on:
  pull_request:
    branches:
      - main
    paths:
      - "ui/**"
      - "!ui/.env"
      - "!ui/README.md"

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install packages
        run: npm i
        working-directory: ui

      - name: Run TypeScript compiler
        run: npm run tsc
        working-directory: ui

      - name: Run ESLint
        run: npm run lint
        working-directory: ui
    permissions:
      contents: read
      pull-requests: read
      checks: write

  build:
    needs: lint
    strategy:
      matrix:
        platform: ["arm64", "amd64"]
        include:
          - platform: arm64
            runner: ubuntu-24.04-arm
          - platform: amd64
            runner: ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          push: false
          platforms: linux/${{ matrix.platform }}
