# Copyright 2023 Daniël Sonck, Piotr Łoboda.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the GNU Affero General Public License v3.0 only, included in the file
# licenses/AGPL.txt.

name: Lint voltaserve/language

on:
  pull_request:
    branches:
      - main
    paths:
      - "language/**"
      
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install flake8
        run: pip install flake8

      - name: Lint using flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: linting
    permissions:
      contents: read
      pull-requests: read
      checks: write
